ALTER TABLE admins
    ADD COLUMN IF NOT EXISTS activation_token TEXT,
    ADD COLUMN IF NOT EXISTS token_expires_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS is_active         BOOLEAN NOT NULL DEFAULT FALSE;